### PR TITLE
Scalable Cards

### PR DESCRIPTION
**Pull request by mayleenliu**

### CODE REVIEW

**Comment by j-wielg** [comment]
So, two main things need to change before this gets merged:
- Control node
At the moment, there is no reason to have `Control` be the root-level node. `MarginContainer` should be the root level node.
- Texture filter
The global project settings currently use the nearest setting for texture filters. This is good for pixel art since it prevents blurring the pixels. However, it makes conventional art and text very pixelated. Under `MarginContainer/Texture` in the inspector, change `filter` to either `Linear`, `Linear Mipmap`, or `Linear Mipmap Anisotropic`

If you guys want, I can add a commit to the branch implementing these things, or you can do it

**Comment by j-wielg** [comment]
Also, the images do not look good when they are shrunk down. However, we can always just merge the branch now and fix it in the future
Screenshot 2024-03-07 130401

**Review by j-wielg — CHANGES_REQUESTED** [review]
See comments above for requested changes

**Comment by mayleenliu** [comment]
Fix for comments above

**Comment by JerrickBan** [comment]
How small are you making the cards?

**Review by j-wielg — APPROVED** [review]

**Review by JerrickBan — APPROVED** [review]

**Pull request merged**
