### PR TITLE
Character Sprite Upload (New card for diff faction)

### PR DESCRIPTION
**Pull request by siscalie**

### CODE REVIEW

**Review by AnthonyBatt — CHANGES_REQUESTED** [review]
@siscalie Very cool sprite, however, the png is currently 32x32, if you could change it to be 64x64 then it will be all good to pull in and merge.

**Comment by siscalie** [comment]
Hi! Here is the resized png file, thanks so much!
Resized Hero Sprite

**Comment by AnthonyBatt** [comment]
Sorry for the confusion, we need you to upload the 64x64 image to the pull request, otherwise we don't have access to it

**Review by AnthonyBatt — APPROVED** [review]
Thank you  for the resize, and thank you for contributing!

**Pull request merged**
