### PR TITLE
Luke artwork

### PR DESCRIPTION
**Pull request by lukewarm3**
I have added three art work: a bare ground tile, a castle, and a spearman.

### CODE REVIEW

**Review by j-wielg — CHANGES_REQUESTED** [review]
Sorry for the confusion in the artwork guide, but we actually want every sprite to be the same size (64x64) so that they tile better. When we said that the size should be 60x60, we meant that it should only use that many pixels, but the PNG size should always be 64x64. I have updated the guide to clear up this confusion.

Changes requested
- Make every sprite 64x64
- Add an outline to the spearman to make it easier to see
- We already have a spearman sprite, but we can use it for the armored Spearman. Rename the sprite to `idle_25.png`
- Create a folder `Assets/Building Sprites` and move the `castle.png` to this new folder
- Move the bare ground sprite to `Assets/Tiles`

**Review by AnthonyBatt — CHANGES_REQUESTED** [review]
Once again love the artwork, but a few minor changes would be appreciated:
1. The ground looks perfect no needed changes there, great work
2. The castle should match the imperial faction’s theme as such two minor changes requested
- rename the sprite to be imperial_castle
- Change the coloration of the of it from red to the blue/orange theme
3. Similarly with the spearman we really like the design so we made a new armored spearman troop for it, but still two minor changes are needed:
- rename to idle_25 (this is the armored spearman)
- Change the red coloration to fit the blue/orange theme

**Comment by lukewarm3** [comment]
I have made all the changes as required!

**Review by AnthonyBatt — APPROVED** [review]
Great work! Thank you for the contribution

**Pull request merged**
