### PR TITLE
Imperial Axeman sprite art

### PR DESCRIPTION
**Pull request by fDoughertyND**
@sconaway

### CODE REVIEW

**Comment by SConaway** [comment]
(at'ed so I can grade the guru point)

**Review by AnthonyBatt — CHANGES_REQUESTED** [review]
@fDoughertyND The sprite itself is awesome (I especially love the mustache), but the png is 60x60, not 64x64. If you could fix this and make it 64x64, then it will be all good to pull in and merge.

**Comment by fDoughertyND** [comment]
I uploaded the corrected sprite, please let me know if it was successful or if I need to create a new request or anything

**Review by AnthonyBatt — APPROVED** [review]
Looks all good, thank you for the dimension fix and the overall contribution

**Pull request merged**
